// frontend/src/App.jsx
import { useState, useRef, useEffect } from 'react';
import { Plane, Sparkles } from 'lucide-react';
import Sidebar from './components/Sidebar';
import ChatMessage from './components/ChatMessage';
import ChatInput from './components/ChatInput';
import Settings from './components/Settings';
import TripDetail from './components/TripDetail';
import MapView from './components/MapView';
import { generateMockSession } from './utils/mockTravelData';

const API_URL = 'http://localhost:8000/api/travel/stream';

/**
 * Main App Component
 */
export default function App() {
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);
  const [sessions, setSessions] = useState([]);
  const [currentSessionId, setCurrentSessionId] = useState(null);
  const [isStreaming, setIsStreaming] = useState(false);
  const [currentView, setCurrentView] = useState('chat');
  const [viewData, setViewData] = useState(null);
  const [displayedMessageCount, setDisplayedMessageCount] = useState(50);
  const messagesEndRef = useRef(null);
  const scrollContainerRef = useRef(null);

  const currentSession = sessions.find(s => s.id === currentSessionId);

  // Auto-scroll to bottom when new messages arrive
  useEffect(() => {
    if (currentSession && currentSession.messages.length > 0) {
      messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    }
  }, [currentSession?.messages.length]);

  // Reset displayed message count when switching sessions
  useEffect(() => {
    setDisplayedMessageCount(50);
  }, [currentSessionId]);

  // Handle scroll to load more messages
  useEffect(() => {
    const scrollContainer = scrollContainerRef.current;
    if (!scrollContainer) return;

    const handleScroll = () => {
      const { scrollTop } = scrollContainer;

      // If user scrolled near the top (within 200px), load more messages
      if (scrollTop < 200 && currentSession && displayedMessageCount < currentSession.messages.length) {
        const prevScrollHeight = scrollContainer.scrollHeight;
        const prevScrollTop = scrollContainer.scrollTop;

        setDisplayedMessageCount(prev => Math.min(prev + 20, currentSession.messages.length));

        // Preserve scroll position after loading more
        requestAnimationFrame(() => {
          const newScrollHeight = scrollContainer.scrollHeight;
          scrollContainer.scrollTop = prevScrollTop + (newScrollHeight - prevScrollHeight);
        });
      }
    };

    scrollContainer.addEventListener('scroll', handleScroll);
    return () => scrollContainer.removeEventListener('scroll', handleScroll);
  }, [currentSession, displayedMessageCount]);

  const createNewSession = () => {
    const newSession = {
      id: Date.now().toString(),
      title: 'New Trip',
      messages: [],
      createdAt: Date.now(),
      hasInitialInput: false,
      initialTripData: null
    };
    setSessions(prev => [newSession, ...prev]);
    setCurrentSessionId(newSession.id);
    setCurrentView('chat');
  };

  const loadMockData = (city = 'New York') => {
    const mockSession = generateMockSession(city);
    setSessions(prev => [mockSession, ...prev]);
    setCurrentSessionId(mockSession.id);
    setCurrentView('chat');
  };

  const selectSession = (sessionId) => {
    setCurrentSessionId(sessionId);
    setCurrentView('chat');
  };

  const deleteSession = (sessionId) => {
    setSessions(prev => prev.filter(s => s.id !== sessionId));
    if (currentSessionId === sessionId) {
      const remaining = sessions.filter(s => s.id !== sessionId);
      setCurrentSessionId(remaining.length > 0 ? remaining[0].id : null);
    }
  };

  const addMessage = (message, targetSessionId) => {
    const sid = targetSessionId ?? currentSessionId;
    setSessions(prev => prev.map(session => {
      if (session.id === sid) {
        return {
          ...session,
          messages: [...session.messages, { ...message, id: Date.now() }]
        };
      }
      return session;
    }));
  };

  const markAllStatusCompleted = (targetSessionId) => {
    const sid = targetSessionId ?? currentSessionId;
    setSessions(prev => prev.map(session => {
      if (session.id === sid) {
        return {
          ...session,
          messages: session.messages.map(msg =>
            msg.type === 'status' ? { ...msg, completed: true } : msg
          )
        };
      }
      return session;
    }));
  };

  const updateSessionTitle = (sessionId, title) => {
    setSessions(prev => prev.map(session => {
      if (session.id === sessionId) {
        return { ...session, title };
      }
      return session;
    }));
  };

  const handleNavigate = (view, data) => {
    setCurrentView(view);
    if (data) setViewData(data);
  };

  const handleSubmit = async (data) => {
    // Check for mock data trigger condition
    const isMockTrigger = data.departure === '1' && data.destination === '1' && data.message === 'test';

    if (isMockTrigger) {
      // Load mock data directly instead of calling API
      loadMockData('New York');
      return;
    }

    let sessionId = currentSessionId;
    let session = sessions.find(s => s.id === sessionId);

    // Auto-create a session if none exists
    if (!sessionId) {
      const newSession = {
        id: Date.now().toString(),
        title: `Trip to ${data.destination}`,
        messages: [],
        createdAt: Date.now(),
        hasInitialInput: false,
        initialTripData: null
      };
      setSessions(prev => [newSession, ...prev]);
      setCurrentSessionId(newSession.id);
      sessionId = newSession.id;
      session = newSession;
    }

    // Ensure we're in chat view
    setCurrentView('chat');

    // Use initial trip data for subsequent messages if available
    const tripData = session?.initialTripData || {
      departure: data.departure,
      destination: data.destination,
      dates: data.dates
    };

    const userMessage = {
      type: 'user',
      content: data.message || `Plan a trip to ${tripData.destination}`,
      metadata: {
        departure: tripData.departure,
        destination: tripData.destination,
        dates: tripData.dates
      }
    };
    addMessage(userMessage, sessionId);

    if (!session || session.title === 'New Trip') {
      updateSessionTitle(sessionId, `Trip to ${tripData.destination}`);
    }

    // Save initial trip data and mark that this session has received initial input
    if (!session?.hasInitialInput) {
      setSessions(prev => prev.map(s =>
        s.id === sessionId ? {
          ...s,
          hasInitialInput: true,
          initialTripData: {
            departure: data.departure,
            destination: data.destination,
            dates: data.dates
          }
        } : s
      ));
    }

    setIsStreaming(true);

    try {
      await streamTravelPlan(tripData.departure, tripData.destination, tripData.dates, sessionId);
    } catch (error) {
      addMessage({
        type: 'error',
        content: error.message
      }, sessionId);
    } finally {
      setIsStreaming(false);
    }
  };

  const streamTravelPlan = async (departure, destination, travelDates, sessionId) => {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        departure: departure || '',
        destination,
        travel_dates: travelDates
      })
    });

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let buffer = '';

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split('\n\n');
      buffer = lines.pop() || '';

      for (const line of lines) {
        if (!line.trim()) continue;

        const eventMatch = line.match(/^event: (.+)$/m);
        const dataMatch = line.match(/^data: (.+)$/m);

        if (eventMatch && dataMatch) {
          const eventType = eventMatch[1];
          const data = JSON.parse(dataMatch[1]);

          switch (eventType) {
            case 'status':
              addMessage({ type: 'status', content: data.message }, sessionId);
              break;
            case 'tool_call':
              addMessage({ type: 'tool_call', tool: data.tool, args: data.args }, sessionId);
              break;
            case 'result':
              addMessage({
                type: 'assistant',
                content: data.content,
                structuredData: data.structured_data || [],
              }, sessionId);
              break;
            case 'error':
              addMessage({ type: 'error', content: data.error }, sessionId);
              break;
            case 'done':
              markAllStatusCompleted(sessionId);
              break;
          }
        }
      }
    }
  };

  const renderMainContent = () => {
    switch (currentView) {
      case 'settings':
        return <Settings sessions={sessions} onClearSessions={() => setSessions([])} />;
      case 'tripDetail':
        return (
          <TripDetail
            session={viewData?.session || currentSession}
            onBack={() => setCurrentView('chat')}
            onOpenMap={(data) => handleNavigate('mapView', data)}
            onContinueChat={() => setCurrentView('chat')}
          />
        );
      case 'mapView':
        return (
          <MapView
            session={viewData?.session || currentSession}
            onBack={() => setCurrentView(viewData?.from || 'chat')}
          />
        );
      default:
        return (
          <>
            {/* Top header bar */}
            <div className={`bg-white border-b border-[#E2E8F0] py-4 shadow-sm transition-all duration-300 ${isSidebarOpen ? 'px-6' : 'pl-16 pr-6'}`}>
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-[#6366F1] flex items-center justify-center shadow-sm">
                  <Plane className="w-5 h-5 text-white" />
                </div>
                <div>
                  <h1 className="text-lg font-semibold text-[#0F172A]">
                    {currentSession?.title || 'Smart Travel Planner'}
                  </h1>
                  <p className="text-sm text-[#64748B]">
                    AI-powered travel planning with real-time insights
                  </p>
                </div>
              </div>
            </div>

            {/* Message list area */}
            <div ref={scrollContainerRef} className="flex-1 overflow-y-auto px-6 py-8">
              <div className="max-w-4xl mx-auto">
                {!currentSession || currentSession.messages.length === 0 ? (
                  <EmptyState />
                ) : (
                  <>
                    {/* Load more indicator */}
                    {currentSession.messages.length > displayedMessageCount && (
                      <div className="flex justify-center mb-6">
                        <button
                          onClick={() => setDisplayedMessageCount(prev => Math.min(prev + 20, currentSession.messages.length))}
                          className="px-4 py-2 text-sm font-medium text-[#6366F1] bg-indigo-50 hover:bg-indigo-100 rounded-lg transition-colors"
                        >
                          Load {Math.min(20, currentSession.messages.length - displayedMessageCount)} more messages
                        </button>
                      </div>
                    )}

                    {/* Render only the latest N messages */}
                    {currentSession.messages
                      .slice(-displayedMessageCount)
                      .map((message, index, arr) => (
                        <ChatMessage
                          key={message.id}
                          message={message}
                          isLatest={index === arr.length - 1}
                        />
                      ))}
                    <div ref={messagesEndRef} />
                  </>
                )}
              </div>
            </div>

            {/* Input area */}
            <ChatInput
              onSubmit={handleSubmit}
              isLoading={isStreaming}
              hasInitialInput={currentSession?.hasInitialInput || false}
            />
          </>
        );
    }
  };

  return (
    <div className="flex h-screen bg-[#F8FAFC] overflow-hidden">
      {/* Sidebar */}
      <Sidebar
        isOpen={isSidebarOpen}
        onToggle={() => setIsSidebarOpen(!isSidebarOpen)}
        sessions={sessions}
        currentSessionId={currentSessionId}
        onSelectSession={selectSession}
        onNewSession={createNewSession}
        onDeleteSession={deleteSession}
        onNavigate={handleNavigate}
        currentView={currentView}
      />

      {/* Main content area */}
      <div
        className={`
          flex-1 flex flex-col transition-all duration-300
          ${isSidebarOpen ? 'ml-64' : 'ml-0'}
        `}
      >
        {renderMainContent()}
      </div>
    </div>
  );
}

function EmptyState() {
  return (
    <div className="flex flex-col items-center justify-center text-center py-16">
      <div className="w-20 h-20 rounded-full bg-indigo-50 flex items-center justify-center mb-6">
        <Sparkles className="w-10 h-10 text-[#6366F1]" />
      </div>
      <h2 className="text-2xl font-semibold text-[#0F172A] mb-3">
        Welcome to Smart Travel Planner
      </h2>
      <p className="text-[#64748B] mb-10 max-w-md leading-relaxed">
        Plan your perfect trip with AI-powered recommendations based on real-time weather data
      </p>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-5 max-w-2xl w-full">
        <FeatureCard
          icon="🌤️"
          title="Weather Insights"
          description="Get accurate forecasts for your destination"
        />
        <FeatureCard
          icon="👕"
          title="Smart Packing"
          description="Personalized clothing and gear recommendations"
        />
        <FeatureCard
          icon="🎯"
          title="Activity Ideas"
          description="Weather-suitable activities for your trip"
        />
      </div>
      <p className="text-xs text-[#94A3B8] mt-10">
        Click <span className="font-semibold text-[#6366F1]">+ New Trip Planning</span> in the sidebar, or just type below
      </p>
    </div>
  );
}

function FeatureCard({ icon, title, description }) {
  return (
    <div className="bg-white rounded-xl p-5 border border-[#E2E8F0] shadow-sm hover:shadow-md transition-all duration-200 hover:-translate-y-1 cursor-default text-left">
      <div className="text-3xl mb-3">{icon}</div>
      <h3 className="font-semibold text-[#0F172A] mb-1">{title}</h3>
      <p className="text-sm text-[#64748B] leading-relaxed">{description}</p>
    </div>
  );
}

// frontend_examples/vue/App.vue
<template>
  <div class="min-h-screen bg-[#F8FAFC]">
    <div class="container mx-auto px-4 py-10 max-w-4xl">
      <!-- Header -->
      <div class="text-center mb-10">
        <h1 class="text-4xl font-bold text-[#0F172A] mb-3">
          ✈️ Smart Travel Planner
        </h1>
        <p class="text-[#64748B] text-lg">
          AI-powered travel planning with real-time weather insights
        </p>
      </div>

      <!-- Form Card -->
      <div class="bg-white rounded-xl shadow-sm border border-[#E2E8F0] p-8 mb-8 hover:shadow-md transition-shadow duration-200">
        <form @submit.prevent="handleSubmit">
          <div class="grid md:grid-cols-2 gap-5 mb-6">
            <!-- Destination Input -->
            <div>
              <label class="block text-sm font-medium text-[#0F172A] mb-2">
                📍 Destination
              </label>
              <input
                v-model="destination"
                type="text"
                placeholder="e.g., Tokyo, Paris, New York"
                :disabled="isStreaming"
                class="w-full px-4 py-2.5 border border-[#E2E8F0] rounded-lg focus:ring-2 focus:ring-[#6366F1] focus:border-transparent outline-none transition-all text-[#0F172A] placeholder:text-[#64748B]"
              />
            </div>

            <!-- Travel Dates Input -->
            <div>
              <label class="block text-sm font-medium text-[#0F172A] mb-2">
                📅 Travel Dates
              </label>
              <input
                v-model="travelDates"
                type="text"
                placeholder="e.g., May 15-20, 2026"
                :disabled="isStreaming"
                class="w-full px-4 py-2.5 border border-[#E2E8F0] rounded-lg focus:ring-2 focus:ring-[#6366F1] focus:border-transparent outline-none transition-all text-[#0F172A] placeholder:text-[#64748B]"
              />
            </div>
          </div>

          <!-- Submit Button -->
          <button
            type="submit"
            :disabled="isStreaming || !destination.trim() || !travelDates.trim()"
            class="w-full bg-[#6366F1] hover:bg-indigo-600 active:bg-indigo-700 disabled:bg-slate-300 text-white font-semibold py-3 px-6 rounded-lg transition-all duration-200 flex items-center justify-center hover:shadow-md"
          >
            <span v-if="isStreaming" class="flex items-center">
              <svg class="animate-spin w-5 h-5 mr-2" fill="none" viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              Planning Your Trip...
            </span>
            <span v-else>Generate Travel Guide</span>
          </button>
        </form>
      </div>

      <!-- Status Display -->
      <div v-if="status" class="bg-indigo-50 border-l-4 border-[#6366F1] p-4 mb-5 rounded-lg">
        <div class="flex items-center">
          <svg class="animate-spin w-5 h-5 text-[#6366F1] mr-3" fill="none" viewBox="0 0 24 24">
            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
          </svg>
          <p class="text-indigo-700 font-medium">{{ status }}</p>
        </div>
      </div>

      <!-- Tool Calls Display -->
      <div v-if="toolCalls.length > 0" class="bg-white border border-[#E2E8F0] p-5 mb-5 rounded-xl shadow-sm">
        <h3 class="font-semibold text-[#0F172A] mb-3">🔧 AI Actions:</h3>
        <div v-for="(call, idx) in toolCalls" :key="idx" class="text-sm text-[#64748B] mb-1.5 flex items-center gap-2">
          <span class="text-[#10B981]">✓</span>
          Called <code class="bg-indigo-50 text-[#6366F1] px-2 py-0.5 rounded text-xs font-medium">{{ call.tool }}</code>
          <span v-if="call.args.city"> for {{ call.args.city }}</span>
        </div>
      </div>

      <!-- Error Display -->
      <div v-if="error" class="bg-red-50 border-2 border-[#EF4444]/30 p-5 mb-5 rounded-xl shadow-sm">
        <div class="flex items-center gap-2">
          <span class="text-[#EF4444]">⚠️</span>
          <p class="text-[#64748B]">{{ error }}</p>
        </div>
      </div>

      <!-- Result Display -->
      <div v-if="result" class="bg-white rounded-xl shadow-sm border border-[#E2E8F0] p-8 hover:shadow-md transition-shadow duration-200">
        <h2 class="text-2xl font-bold text-[#0F172A] mb-4 flex items-center">
          <span class="text-[#10B981] mr-2">✓</span>
          Your Travel Guide
        </h2>
        <div class="prose prose-sm max-w-none">
          <pre class="whitespace-pre-wrap font-sans text-[#0F172A] leading-relaxed">{{ result }}</pre>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';

const destination = ref('');
const travelDates = ref('');
const status = ref('');
const toolCalls = ref([]);
const result = ref('');
const error = ref('');
const isStreaming = ref(false);

const handleSubmit = async () => {
  if (!destination.value.trim() || !travelDates.value.trim()) return;

  status.value = '';
  toolCalls.value = [];
  result.value = '';
  error.value = '';
  isStreaming.value = true;

  try {
    const response = await fetch('http://localhost:8000/api/travel/stream', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        destination: destination.value,
        travel_dates: travelDates.value
      })
    });

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let buffer = '';

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split('\n\n');
      buffer = lines.pop() || '';

      for (const line of lines) {
        if (!line.trim()) continue;

        const eventMatch = line.match(/^event: (.+)$/m);
        const dataMatch = line.match(/^data: (.+)$/m);

        if (eventMatch && dataMatch) {
          const eventType = eventMatch[1];
          const data = JSON.parse(dataMatch[1]);

          switch (eventType) {
            case 'status':
              status.value = data.message;
              break;
            case 'tool_call':
              toolCalls.value.push({
                tool: data.tool,
                args: data.args
              });
              break;
            case 'result':
              result.value = data.content;
              break;
            case 'error':
              error.value = data.error;
              break;
            case 'done':
              status.value = 'Travel guide generated successfully!';
              break;
          }
        }
      }
    }
  } catch (err) {
    error.value = err.message;
  } finally {
    isStreaming.value = false;
  }
};
</script>

<style scoped>
/* Optional: Add custom styles if needed */
</style>
